version: '3'
services:
  app:
    build:
      context: .
      dockerfile: DockerfileDebug
    container_name: api-master
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app/src
      - ./node_modules:/app/node_modules
    command: npm run start:dev
    networks:
      - local
  mongo:
    image: mongo
    container_name: mongo-master
    ports:
      - "27017:27017"
    networks:
      - local
  minio-master:
    image: minio/minio:latest
    container_name: minio-master
    ports:
      - "9000:9072"
    environment:
      MINIO_ROOT_USER: admin1234567
      MINIO_ROOT_PASSWORD: admin1234567
    command: ["minio", "server", "/data"]
    volumes:
      - minio-data:/data
    networks:
      - local
networks:
  local:
    name: local
volumes:
  minio-data:
